# Generated by Django 3.1.5 on 2021-01-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
    ]
